# Generated by Django 5.1.5 on 2025-02-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kufar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='kufar_app.phoneimage'),
        ),
    ]
