# Generated by Django 5.1.5 on 2025-02-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kufar_app', '0002_phones_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='image',
        ),
    ]
