# Generated by Django 5.1.5 on 2025-02-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kufar_app', '0005_remove_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('phone', 'Телефон'), ('computer', 'Компьютер'), ('car', 'Машина'), ('tablet', 'Планшет')], max_length=20, verbose_name='Тип товара')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_item_img', models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\KufarProject\\kufar/media/')),
                ('announcement_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kufar_app.announcement')),
            ],
        ),
    ]
