# Generated by Django 5.1.5 on 2025-02-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kufar_app', '0006_announcement_announcementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=4)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=4)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=4)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Phones',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='item',
            new_name='item_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\KufarProject\\kufar/media/cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kufar_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\KufarProject\\kufar/media/computers/')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kufar_app.computer')),
            ],
        ),
        migrations.CreateModel(
            name='TabletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\KufarProject\\kufar/media/tablets/')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kufar_app.tablet')),
            ],
        ),
    ]
