# Generated by Django 5.1.5 on 2025-02-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kufar_app', '0007_car_computer_tablet_rename_phones_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementimage',
            name='announcement_item',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementImage',
        ),
    ]
