# Generated by Django 5.1.5 on 2025-02-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kufar_app', '0008_remove_announcementimage_announcement_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tablet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kufar_app.tablet'),
            preserve_default=False,
        ),
    ]
